use cc_memory::db::MemoryDatabase;
use cc_memory::models::*;
use cc_memory::repository::MemoryRepository;
use cc_memory::service::MemoryService as CoreMemoryService;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

/// Tauri 层 Memory 服务包装
///
/// 包装 cc_memory crate 的 CoreMemoryService，将 Result<T, String> 转为 AppResult<T>。
/// 额外提供 prepare_session_context 等 Tauri 特有功能。
pub struct MemoryService {
    core: CoreMemoryService,
}

impl MemoryService {
    /// 从文件路径创建（生产环境）
    pub fn new(db_path: PathBuf) -> Result<Self, String> {
        let db = MemoryDatabase::new(db_path)?;
        let repo = MemoryRepository::new(db);
        let core = CoreMemoryService::new(repo);
        Ok(Self { core })
    }

    /// 内存数据库（降级 / 测试用）
    pub fn new_memory() -> Result<Self, String> {
        let db = MemoryDatabase::new_memory()?;
        let repo = MemoryRepository::new(db);
        let core = CoreMemoryService::new(repo);
        Ok(Self { core })
    }

    // ============ 转发方法 ============

    /// 存储新 Memory
    pub fn store(&self, req: StoreMemoryRequest) -> Result<Memory, String> {
        self.core.store(req)
    }

    /// 搜索
    pub fn search(&self, query: MemoryQuery) -> Result<MemoryQueryResult, String> {
        self.core.search(query)
    }

    /// 列表（无搜索词）
    pub fn list(
        &self,
        scope: Option<MemoryScope>,
        workspace_name: Option<&str>,
        project_path: Option<&str>,
        limit: Option<u32>,
        offset: Option<u32>,
    ) -> Result<MemoryQueryResult, String> {
        self.core
            .list(scope, workspace_name, project_path, limit, offset)
    }

    /// 按 ID 获取
    pub fn get(&self, id: &str) -> Result<Option<Memory>, String> {
        self.core.get(id)
    }

    /// 更新
    pub fn update(&self, id: &str, req: UpdateMemoryRequest) -> Result<bool, String> {
        self.core.update(id, req)
    }

    /// 删除
    pub fn delete(&self, id: &str) -> Result<bool, String> {
        self.core.delete(id)
    }

    /// 统计
    pub fn stats(
        &self,
        workspace_name: Option<&str>,
        project_path: Option<&str>,
    ) -> Result<MemoryStats, String> {
        self.core.stats(workspace_name, project_path)
    }

    /// 格式化 Memory 为 Markdown（用于注入）
    pub fn format_for_injection(&self, ids: &[String]) -> Result<String, String> {
        self.core.format_for_injection(ids)
    }

    /// 获取项目摘要（高重要度 Memory）
    pub fn get_project_summary(
        &self,
        project_path: &str,
        min_importance: u8,
        limit: u32,
    ) -> Result<Vec<Memory>, String> {
        self.core
            .get_project_summary(project_path, min_importance, limit)
    }

    // ============ Tauri 特有方法 ============

    /// 准备会话上下文：合并指定 Memory + 项目核心 Memory，写入 CLAUDE.local.md
    ///
    /// 1. 从 memory_ids 获取 Memory 内容
    /// 2. 自动补充该项目 importance >= 4 的核心 Memory
    /// 3. 合并去重
    /// 4. 生成 Markdown 格式内容
    /// 5. 写入 <project_path>/CLAUDE.local.md
    /// 6. 确保 .gitignore 包含 CLAUDE.local.md
    /// 7. 返回写入内容
    pub fn prepare_session_context(
        &self,
        project_path: &str,
        memory_ids: &[String],
    ) -> Result<String, String> {
        // 收集指定的 Memory
        let mut all_memories: Vec<Memory> = Vec::new();
        let mut seen_ids: HashSet<String> = HashSet::new();

        for id in memory_ids {
            if let Some(memory) = self.core.get(id)? {
                if seen_ids.insert(memory.id.clone()) {
                    all_memories.push(memory);
                }
            }
        }

        // 补充项目核心 Memory（importance >= 4）
        let core_memories = self.core.get_project_summary(project_path, 4, 20)?;
        for memory in core_memories {
            if seen_ids.insert(memory.id.clone()) {
                all_memories.push(memory);
            }
        }

        if all_memories.is_empty() {
            return Ok(String::new());
        }

        // 按 importance 降序排列
        all_memories.sort_by_key(|memory| std::cmp::Reverse(memory.importance));

        // 生成 Markdown 内容
        let content = format_memories_markdown(&all_memories);

        // 写入 CLAUDE.local.md
        let project_dir = Path::new(project_path);
        let local_md_path = project_dir.join("CLAUDE.local.md");

        std::fs::write(&local_md_path, &content)
            .map_err(|e| format!("Failed to write CLAUDE.local.md: {}", e))?;

        // 确保 .gitignore 包含 CLAUDE.local.md
        ensure_gitignore_entry(project_dir)?;

        Ok(content)
    }
}

/// 将 Memory 列表格式化为 Markdown
fn format_memories_markdown(memories: &[Memory]) -> String {
    let mut md = String::from("# Session Context (Auto-generated)\n\n");
    md.push_str(
        "> This file is auto-generated by CC-Panes Memory system. Do not edit manually.\n\n",
    );

    for memory in memories {
        md.push_str(&format!(
            "## {} [{}/{}]\n\n",
            memory.title, memory.scope, memory.category
        ));
        md.push_str(&format!("{}\n\n", memory.content));
        if !memory.tags.is_empty() {
            md.push_str(&format!("Tags: {}\n\n", memory.tags.join(", ")));
        }
        md.push_str("---\n\n");
    }

    md
}

/// 确保 .gitignore 包含 CLAUDE.local.md
fn ensure_gitignore_entry(project_dir: &Path) -> Result<(), String> {
    let gitignore_path = project_dir.join(".gitignore");
    let entry = "CLAUDE.local.md";

    if gitignore_path.exists() {
        let content = std::fs::read_to_string(&gitignore_path)
            .map_err(|e| format!("Failed to read .gitignore: {}", e))?;

        // 检查是否已包含
        let already_present = content.lines().any(|line| line.trim() == entry);
        if already_present {
            return Ok(());
        }

        // 追加条目
        let separator = if content.ends_with('\n') { "" } else { "\n" };
        let new_content = format!("{}{}{}\n", content, separator, entry);
        std::fs::write(&gitignore_path, new_content)
            .map_err(|e| format!("Failed to write .gitignore: {}", e))?;
    } else {
        // 创建新的 .gitignore
        std::fs::write(&gitignore_path, format!("{}\n", entry))
            .map_err(|e| format!("Failed to create .gitignore: {}", e))?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> MemoryService {
        MemoryService::new_memory().expect("Failed to create in-memory MemoryService")
    }

    #[test]
    fn test_store_and_get() {
        let service = setup();
        let req = StoreMemoryRequest {
            title: "Test Memory".to_string(),
            content: "Test content".to_string(),
            scope: Some(MemoryScope::Global),
            ..Default::default()
        };

        let memory = service.store(req).unwrap();
        assert_eq!(memory.title, "Test Memory");

        let found = service.get(&memory.id).unwrap();
        assert!(found.is_some());
        assert_eq!(found.unwrap().title, "Test Memory");
    }

    #[test]
    fn test_search() {
        let service = setup();
        let req = StoreMemoryRequest {
            title: "Searchable Item".to_string(),
            content: "Unique content for search test".to_string(),
            scope: Some(MemoryScope::Global),
            ..Default::default()
        };
        service.store(req).unwrap();

        let query = MemoryQuery {
            search: Some("Searchable".to_string()),
            ..Default::default()
        };
        let result = service.search(query).unwrap();
        assert!(!result.items.is_empty());
    }

    #[test]
    fn test_update_and_delete() {
        let service = setup();
        let req = StoreMemoryRequest {
            title: "To Update".to_string(),
            content: "Original".to_string(),
            scope: Some(MemoryScope::Global),
            ..Default::default()
        };
        let memory = service.store(req).unwrap();

        let update_req = UpdateMemoryRequest {
            title: Some("Updated Title".to_string()),
            ..Default::default()
        };
        let updated = service.update(&memory.id, update_req).unwrap();
        assert!(updated);

        let deleted = service.delete(&memory.id).unwrap();
        assert!(deleted);

        let found = service.get(&memory.id).unwrap();
        assert!(found.is_none());
    }

    #[test]
    fn test_list_and_stats() {
        let service = setup();

        // 创建几条 Memory
        for i in 0..3 {
            let req = StoreMemoryRequest {
                title: format!("Memory {}", i),
                content: format!("Content {}", i),
                scope: Some(MemoryScope::Global),
                ..Default::default()
            };
            service.store(req).unwrap();
        }

        let result = service.list(None, None, None, None, None).unwrap();
        assert_eq!(result.total, 3);

        let stats = service.stats(None, None).unwrap();
        assert_eq!(stats.total, 3);
    }

    #[test]
    fn test_format_for_injection() {
        let service = setup();
        let req = StoreMemoryRequest {
            title: "Inject Me".to_string(),
            content: "Important context".to_string(),
            scope: Some(MemoryScope::Global),
            ..Default::default()
        };
        let memory = service.store(req).unwrap();

        let md = service.format_for_injection(&[memory.id.clone()]).unwrap();
        assert!(md.contains("Inject Me"));
        assert!(md.contains("Important context"));
    }

    #[test]
    fn test_prepare_session_context_empty() {
        let service = setup();
        let result = service
            .prepare_session_context("/nonexistent/path", &[])
            .unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_format_memories_markdown() {
        let memories = vec![Memory {
            id: "test-id".to_string(),
            title: "Test".to_string(),
            content: "Hello world".to_string(),
            scope: MemoryScope::Project,
            category: MemoryCategory::Fact,
            importance: 5,
            workspace_name: None,
            project_path: None,
            session_id: None,
            tags: vec!["rust".to_string()],
            source: "user".to_string(),
            created_at: "2025-01-01T00:00:00Z".to_string(),
            updated_at: "2025-01-01T00:00:00Z".to_string(),
            accessed_at: "2025-01-01T00:00:00Z".to_string(),
            access_count: 0,
            user_id: None,
            sync_status: "local_only".to_string(),
            sync_version: 0,
            is_deleted: false,
        }];

        let md = format_memories_markdown(&memories);
        assert!(md.contains("# Session Context"));
        assert!(md.contains("## Test [project/fact]"));
        assert!(md.contains("Hello world"));
        assert!(md.contains("Tags: rust"));
    }
}
